env:
  browser: true
  es2021: true
extends:
  - plugin:vue/base
  - plugin:vue/vue3-recommended
  - plugin:@typescript-eslint/recommended
  - '@nuxtjs/eslint-config-typescript'
ignorePatterns:
  - "**/.nuxt/*"
  - "**/dist/*"
overrides: []
parser: 'vue-eslint-parser'
parserOptions:
  parser: "@typescript-eslint/parser"
  ecmaVersion: latest
  ecmaFeatures: 
    jsx: true
  sourceType: module
plugins:
  - vue
  - '@typescript-eslint'
rules: 
  "@typescript-eslint/no-unused-vars": "off"
  no-unused-vars: "off"
    
